### ISSUE TITLE
Create quick preview for list items

### ISSUE THREAD

**Issue by James-Millan** [spe-uob/2021-HiddenMuseum#64] opened 2021-12-17 17:00 UTC
When you search for an item, you have the item name at the top of the list item. Then underneath, there should be some text from the information on the item. This is similar to how information is displayed on search engines like Google and Bing.

**Comment by baconsenpaii** [comment] 2022-02-22 20:20
Duplicate of #83 (this was not added to the Kanban so it was likely missed, with the issue recreated)

**Closed by baconsenpaii** 2022-02-22 20:20 UTC
Labels: duplicate, enhancement
